In [ ]:
import numpy as np
from scipy.linalg import kron

def spin_operators(S):
    """Returns the spin operators Sx, Sy, Sz for a given spin quantum number S."""
    dim = int(2 * S + 1)
    m = np.arange(S, -S-1, -1)  # m values
    Sx = np.zeros((dim, dim))
    Sy = np.zeros((dim, dim))
    Sz = np.diag(m)
    
    for i in range(dim - 1):
        Sx[i, i + 1] = 0.5 * np.sqrt((S - m[i]) * (S + m[i + 1]))
        Sx[i + 1, i] = 0.5 * np.sqrt((S - m[i]) * (S + m[i + 1]))
        Sy[i, i + 1] = -0.5 * np.sqrt((S - m[i]) * (S + m[i + 1]))
        Sy[i + 1, i] = 0.5 * np.sqrt((S - m[i + 1]) * (S + m[i]))
    
    return Sx, Sy, Sz

def construct_hamiltonian(S, Ns, B, g_tensor, J_tensor):
    """
    Constructs the Hamiltonian for a system of Ns spins with spin quantum number S.
    Includes external field and spin-spin interaction terms.
    """
    # Spin operators for a single spin
    Sx, Sy, Sz = spin_operators(S)
    dim = int(2 * S + 1)
    
    # Total dimension of the Hilbert space
    hilbert_dim = dim ** Ns
    
    # External field term
    H_ext = np.zeros((hilbert_dim, hilbert_dim), dtype=np.complex128)
    for i in range(Ns):
        Sx_total = np.eye(1)
        Sy_total = np.eye(1)
        Sz_total = np.eye(1)
        print(Sy_total)
        for j in range(Ns):
            if j == i:
                Sx_total = kron(Sx_total, Sx)
                Sy_total = kron(Sy_total, Sy)
                Sz_total = kron(Sz_total, Sz)
            else:
                Sx_total = kron(Sx_total, np.eye(dim))
                Sy_total = kron(Sy_total, np.eye(dim))
                Sz_total = kron(Sz_total, np.eye(dim))
        print(Sz_total)
        # Add g-tensor contributions
        H_ext += B[0] * g_tensor[i][0] * Sx_total
        H_ext += B[1] * g_tensor[i][1] * Sy_total
        H_ext += B[2] * g_tensor[i][2] * Sz_total
    
    # Spin-spin interaction term
    H_spin_spin = np.zeros((hilbert_dim, hilbert_dim), dtype=np.complex128)
    for i in range(Ns):
        for j in range(i + 1, Ns):
            J = J_tensor[i][j]
            for op1, op2, J_comp in zip([Sx, Sy, Sz], [Sx, Sy, Sz], J):
                Si = np.eye(1)
                Sj = np.eye(1)
                for k in range(Ns):
                    if k == i:
                        Si = kron(Si, op1)
                    else:
                        Si = kron(Si, np.eye(dim))
                    if k == j:
                        Sj = kron(Sj, op2)
                    else:
                        Sj = kron(Sj, np.eye(dim))
                H_spin_spin += J_comp * Si @ Sj
    
    # Total Hamiltonian
    H_total = H_ext + H_spin_spin
    
    return H_total

# Parameters
S = 0.5  # Spin quantum number (spin-1/2)
Ns = 2   # Number of spins
B = [1.0, 0.0, 0.5]  # Magnetic field vector (Bx, By, Bz)
g_tensor = np.zeros((Ns, 3, 3), dtype=np.float64)  # g-tensor

for i in range(Ns):
    g_tensor[i] = np.eye(3)

J_tensor = np.zeros((Ns,Ns, 3, 3), dtype=np.float64)
    
for i in range(Ns):
    for j in range(Ns):
        J_tensor[i,j] = np.eye(3) 
# Construct the Hamiltonian
H_total = construct_hamiltonian(S, Ns, B, g_tensor, J_tensor)

# Print the Hamiltonian
print("Hamiltonian matrix:")
print(H_total)

# Check memory usage
print(f"Hamiltonian matrix size: {H_total.nbytes / (1024 ** 2):.2f} MB")


[[1.]]
[[ 0.5  0.   0.   0. ]
 [ 0.   0.5  0.   0. ]
 [ 0.   0.  -0.5 -0. ]
 [ 0.   0.  -0.  -0.5]]


ValueError: operands could not be broadcast together with shapes (3,) (4,4) 

In [1]:
import numpy as np

dim = 3  # Dimension of the spin-1 system
N_s = 2  # Number of spins you want in the Hilbert space
Sx = ...  # Define your spin-1 Sx matrix

# Initialize Sx_total
Sx_total = np.eye(1)

# Construct the total Sx operator for N_s = 2 spins
for i in range(N_s):
    if i == 0:
        Sx_total = np.kron(Sx_total, Sx)
    else:
        Sx_total = np.kron(Sx_total, np.eye(dim))

print("Shape of Sx_total:", Sx_total.shape) 

TypeError: unsupported operand type(s) for *: 'float' and 'ellipsis'

In [5]:
import numpy as np

# Spin quantum number
S = 1
m_values = np.array([-1, 0, 1])  # Magnetic quantum numbers
dim = len(m_values)  # Dimension of the Hilbert space

# Initialize spin operator matrices
Sx = np.zeros((dim, dim), dtype=complex)
Sy = np.zeros((dim, dim), dtype=complex)
Sz = np.zeros((dim, dim), dtype=complex)

# Compute matrix elements
for i, m in enumerate(m_values):  # m is the row index
    for j, m_prime in enumerate(m_values):  # m' is the column index
        # Sx
        if m_prime == m + 1 or m_prime == m - 1:
            Sx[j, i] = 0.5 * np.sqrt(S * (S + 1) - m * m_prime)

        # Sy
        if m_prime == m + 1:
            Sy[j, i] = -0.5j * np.sqrt(S * (S + 1) - m * m_prime)
        elif m_prime == m - 1:
            Sy[j, i] = 0.5j * np.sqrt(S * (S + 1) - m * m_prime)

        # Sz
        if m_prime == m:
            Sz[j, i] = m

# Print the matrices
print("Sx:\n", Sx.real)
print("Sy:\n", Sy)
print("Sz:\n", Sz.real)

Sx:
 [[0.         0.70710678 0.        ]
 [0.70710678 0.         0.70710678]
 [0.         0.70710678 0.        ]]
Sy:
 [[0.+0.j         0.+0.70710678j 0.+0.j        ]
 [0.-0.70710678j 0.+0.j         0.+0.70710678j]
 [0.+0.j         0.-0.70710678j 0.+0.j        ]]
Sz:
 [[-1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]]


In [14]:
import numpy as np

print(np.eye(3))

print(np.kron(np.eye(3), np.ones((3,3))))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]]


In [27]:
N=3

Sx = np.ones((3,3))

for i in range(N):
    Sx_total = np.eye(1)

    for j in range(2):
        if j == i:
            Sx_total = kron(Sx_total, Sx)

        else:
            Sx_total = kron(Sx_total, np.eye(N))
    print(Sx_total)

[[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]
[[1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [30]:
Sx_total = np.eye(N)


Sx_total = np.kron(Sx,Sx_total )

print(Sx_total)

[[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]


In [31]:
import numpy as np

class Example:
    def __init__(self):
        # Initialize 3x3 matrices
        self.Sx = np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]])
        self.Sy = np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 1]])
        self.Sz = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

    def print_matrices(self):
        # Iterate over the matrices and print each one with its index
        for a, op1 in enumerate([self.Sx, self.Sy, self.Sz]):
            print(f"Matrix {a}:\n{op1}\n")

example = Example()
example.print_matrices()

Matrix 0:
[[ 1  0  0]
 [ 0  0 -1]
 [ 0  1  0]]

Matrix 1:
[[ 0  1  0]
 [-1  0  0]
 [ 0  0  1]]

Matrix 2:
[[0 0 1]
 [0 1 0]
 [1 0 0]]

