In [2]:
import numpy as np
from scipy.optimize import curve_fit

# Define the polynomial function
def poly_func(coords, a0, a1, a2, a3, a4, a5):
    x, y = coords
    return a0 + a1*x + a2*y + a3*x**2 + a4*y**2 + a5*x*y

# Displacements (x, y) and corresponding H_s values
displacements = np.array([[-0.1, -0.1], [-0.1, 0.0], [-0.1, 0.1],
                          [0.0, -0.1], [0.0, 0.0], [0.0, 0.1],
                          [0.1, -0.1], [0.1, 0.0], [0.1, 0.1]])
Hs_values = np.array([Hs1, Hs2, Hs3, Hs4, Hs5, Hs6, Hs7, Hs8, Hs9])  # Replace with actual values

# Fit the polynomial to the data
coords = (displacements[:, 0], displacements[:, 1])  # x and y displacements
popt, _ = curve_fit(poly_func, coords, Hs_values)

# Extract coefficients
a0, a1, a2, a3, a4, a5 = popt

# Compute second derivatives
d2Hs_dx2 = 2 * a3
d2Hs_dy2 = 2 * a4
d2Hs_dxdy = a5

print(f"Second derivative with respect to x^2: {d2Hs_dx2}")
print(f"Second derivative with respect to y^2: {d2Hs_dy2}")
print(f"Mixed second derivative (dxdy): {d2Hs_dxdy}")

NameError: name 'Hs1' is not defined

In [3]:
import numpy as np

# Define two 1D arrays of length 10
array1 = np.arange(10)
array2 = np.arange(10, 20)

# Create a 2D array of size 10x10
# Using broadcasting to combine the two arrays into a 2D array
array_2d = np.array([array1 + i for i in array2])

# Print the 2D array
print("1D Array 1:")
print(array1)
print("\n1D Array 2:")
print(array2)
print("\n2D Array (10x10):")
print(array_2d)

1D Array 1:
[0 1 2 3 4 5 6 7 8 9]

1D Array 2:
[10 11 12 13 14 15 16 17 18 19]

2D Array (10x10):
[[10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]
 [12 13 14 15 16 17 18 19 20 21]
 [13 14 15 16 17 18 19 20 21 22]
 [14 15 16 17 18 19 20 21 22 23]
 [15 16 17 18 19 20 21 22 23 24]
 [16 17 18 19 20 21 22 23 24 25]
 [17 18 19 20 21 22 23 24 25 26]
 [18 19 20 21 22 23 24 25 26 27]
 [19 20 21 22 23 24 25 26 27 28]]


In [4]:
import numpy as np

# Define two 1D arrays of length 10
array1 = np.arange(10)
array2 = np.arange(10, 20)

# Create a 1D array of 2D vectors (each 2D vector is a NumPy array with 2 elements)
array_1d_of_2d_vectors = np.array([[array1[i], array2[i]] for i in range(len(array1))])

# Print the 1D array of 2D vectors
print("1D Array of 2D Vectors:")
print(array_1d_of_2d_vectors)

1D Array of 2D Vectors:
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [6]:
import numpy as np
import itertools

# Define two 1D arrays of length 10
array1 = np.arange(10)
array2 = np.arange(10, 20)

# Generate the Cartesian product of array1 and array2
cartesian_product = list(itertools.product(array1, array2))

# Convert the list of tuples to a NumPy array
cartesian_product_array = np.array(cartesian_product)

# Print the result
print("1D Array 1:")
print(array1)
print("\n1D Array 2:")
print(array2)
print("\nCartesian Product (100 pairs):")
print(cartesian_product_array)

1D Array 1:
[0 1 2 3 4 5 6 7 8 9]

1D Array 2:
[10 11 12 13 14 15 16 17 18 19]

Cartesian Product (100 pairs):
[[ 0 10]
 [ 0 11]
 [ 0 12]
 [ 0 13]
 [ 0 14]
 [ 0 15]
 [ 0 16]
 [ 0 17]
 [ 0 18]
 [ 0 19]
 [ 1 10]
 [ 1 11]
 [ 1 12]
 [ 1 13]
 [ 1 14]
 [ 1 15]
 [ 1 16]
 [ 1 17]
 [ 1 18]
 [ 1 19]
 [ 2 10]
 [ 2 11]
 [ 2 12]
 [ 2 13]
 [ 2 14]
 [ 2 15]
 [ 2 16]
 [ 2 17]
 [ 2 18]
 [ 2 19]
 [ 3 10]
 [ 3 11]
 [ 3 12]
 [ 3 13]
 [ 3 14]
 [ 3 15]
 [ 3 16]
 [ 3 17]
 [ 3 18]
 [ 3 19]
 [ 4 10]
 [ 4 11]
 [ 4 12]
 [ 4 13]
 [ 4 14]
 [ 4 15]
 [ 4 16]
 [ 4 17]
 [ 4 18]
 [ 4 19]
 [ 5 10]
 [ 5 11]
 [ 5 12]
 [ 5 13]
 [ 5 14]
 [ 5 15]
 [ 5 16]
 [ 5 17]
 [ 5 18]
 [ 5 19]
 [ 6 10]
 [ 6 11]
 [ 6 12]
 [ 6 13]
 [ 6 14]
 [ 6 15]
 [ 6 16]
 [ 6 17]
 [ 6 18]
 [ 6 19]
 [ 7 10]
 [ 7 11]
 [ 7 12]
 [ 7 13]
 [ 7 14]
 [ 7 15]
 [ 7 16]
 [ 7 17]
 [ 7 18]
 [ 7 19]
 [ 8 10]
 [ 8 11]
 [ 8 12]
 [ 8 13]
 [ 8 14]
 [ 8 15]
 [ 8 16]
 [ 8 17]
 [ 8 18]
 [ 8 19]
 [ 9 10]
 [ 9 11]
 [ 9 12]
 [ 9 13]
 [ 9 14]
 [ 9 15]
 [ 9 16]
 [ 9 17]
 [ 9 18